name: logo
description: Log for Dart. Simple log package for debug and issue tracking. No extra dependency.
version: 1.1.0
homepage: https://sudo.dog
repository: https://github.com/SudoDotDog/Dart-Logo

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.21.1
